name: momentum
description: A flutter state management library that focuses on ease of control.
version: 1.0.8
homepage: https://github.com/xamantra/momentum
author: xamantra <xamantrx@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.7
#dev_dependencies:
#  pedantic: ^1.8.0
#  test: ^1.6.0
